cat train.out | grep -v "-" |  grep ",unknown" | grep "bed/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "bird/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "cat/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "dog/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "eight/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "five/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "four/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "happy/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "house/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "marvin/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "nine/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "one/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "seven/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "sheila/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "six/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "three/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "tree/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "two/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "wow/" | wc -l
cat train.out | grep -v "-" |  grep ",unknown" | grep "zero/" | wc -l
