cat train.out | grep -v "-" |  grep "bed/" | wc -l
cat train.out | grep -v "-" |  grep "bird/" | wc -l
cat train.out | grep -v "-" |  grep "cat/" | wc -l
cat train.out | grep -v "-" |  grep "dog/" | wc -l
cat train.out | grep -v "-" |  grep "eight/" | wc -l
cat train.out | grep -v "-" |  grep "five/" | wc -l
cat train.out | grep -v "-" |  grep "four/" | wc -l
cat train.out | grep -v "-" |  grep "happy/" | wc -l
cat train.out | grep -v "-" |  grep "house/" | wc -l
cat train.out | grep -v "-" |  grep "marvin/" | wc -l
cat train.out | grep -v "-" |  grep "nine/" | wc -l
cat train.out | grep -v "-" |  grep "one/" | wc -l
cat train.out | grep -v "-" |  grep "seven/" | wc -l
cat train.out | grep -v "-" |  grep "sheila/" | wc -l
cat train.out | grep -v "-" |  grep "six/" | wc -l
cat train.out | grep -v "-" |  grep "three/" | wc -l
cat train.out | grep -v "-" |  grep "tree/" | wc -l
cat train.out | grep -v "-" |  grep "two/" | wc -l
cat train.out | grep -v "-" |  grep "wow/" | wc -l
cat train.out | grep -v "-" |  grep "zero/" | wc -l
