cat train.out | grep -v "-" |  grep ",left"  | grep "left/" | wc -l
cat train.out | grep -v "-" |  grep ",right" | grep "right/" | wc -l
cat train.out | grep -v "-" |  grep ",up"    | grep "up/" | wc -l
cat train.out | grep -v "-" |  grep ",down"  | grep "down/" | wc -l
cat train.out | grep -v "-" |  grep ",on"    | grep "on/" | wc -l
cat train.out | grep -v "-" |  grep ",off"   | grep "off/" | wc -l
cat train.out | grep -v "-" |  grep ",go"    | grep "go/" | wc -l
cat train.out | grep -v "-" |  grep ",stop"  | grep "stop/" | wc -l
cat train.out | grep -v "-" |  grep ",yes"   | grep "yes/" | wc -l
cat train.out | grep -v "-" |  grep ",no"    | grep "no/" | wc -l
